### ISSUE TITLE
Show text efficiency

### ISSUE THREAD

**Issue by laurmaedje** [csimide/cuti#1]
I saw the `show text: show-cn-fakebold` in the README and was wondering whether the `show text` part is really necessary. It will be very inefficient. Since the inner rules already apply to `show text.where(weight: "bold").or(strong)` just applying this rule to everything rather than text elements individually should probably also work.

**Comment by csimide** [comment]
Thank you for bringing this up. Would you suggest changing `show text: show-cn-fakebold` to `show: show-cn-fakebold` as a more efficient solution?

**Comment by laurmaedje** [comment]
That sounds like the correct change. If it works, it should be good!
