### ISSUE TITLE
Code for fake italic and fake small caps.

### ISSUE THREAD

**Issue by Tetragramm** [csimide/cuti#4]
```
#let regex-fakeitalic(reg-exp: "\b.+?\b", ang: -18deg, s) = {
  show regex(reg-exp): it => {
    box(skew(ax: ang, reflow: false, it))
  }
  s
}

#let regex-fakesc(reg-exp: "[a-z]", s) = {
  show regex("[\p{Lu}]"): text.with((10 / 8) * 1em)
  text(0.8em, upper(s))
}
```

The spacing works well for both of these, though you can't get too long (in the multiple pages) with a single invocation.
![image](https://github.com/user-attachments/assets/3b3922b7-f4cb-4975-a6e0-3c91d9d8f705)

Perhaps you can test with the Chinese characters and see if it is working correctly?

**Comment by csimide** [comment]
Thank you for your issue. Your `regex-fakeitalic` function works reasonably well with Chinese characters. One minor issue is that punctuation marks, such as `《` (Chinese book title bracket), are not matched by "\b.+?\b". However, considering the typical use cases for italics, this limitation with punctuation might be acceptable for the time being.

Please consider submitting this code as a Pull Request. This will ensure proper attribution of the code to you as the author. Thanks.
